version = 0.1
[default.deploy.parameters]
stack_name = "aws-spring-cloud-function-kotlin-reactive-sample"
resolve_s3 = true
s3_prefix = "aws-spring-cloud-function-kotlin-reactive-sample"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false